In [142]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import pyreadstat

In [15]:
file_path = ".\\BASEDATOS_ARGENTINA_122_ .sav"

In [29]:
df_diputados, meta = pyreadstat.read_sav(file_path)
df = df_diputados
type(df)

pandas.core.frame.DataFrame

In [37]:
df.head(5)

Encuestado  País   legis  partido  departa  tipoelec  comision01  \
0         4.0   1.0  2022.0     20.0     12.0       2.0         7.0   
1         6.0   1.0  2022.0      7.0      2.0       2.0         2.0   
2        10.0   1.0  2022.0      2.0     15.0       2.0         1.0   
3        11.0   1.0  2022.0      7.0      2.0       2.0         5.0   
4        12.0   1.0  2022.0     29.0      9.0       2.0        37.0   

   comision02  comision03  comision04  ...  pcontacto2  pcontacto3  \
0        16.0        31.0         NaN  ...         NaN         NaN   
1         3.0        15.0        25.0  ...         NaN         NaN   
2         2.0         3.0         4.0  ...         NaN         NaN   
3        15.0        27.0        35.0  ...         NaN         NaN   
4        38.0         NaN         NaN  ...         NaN         NaN   

   resultado1  resultado107  causaneg1  resultado2  causaneg2  resultado3  \
0         1.0                      NaN         NaN        NaN         NaN   
1         1.0                      NaN         NaN        NaN         NaN   
2         1.0                      NaN         NaN        NaN         NaN   
3         1.0                      NaN         NaN        NaN         NaN   
4         1.0                      NaN         NaN        NaN         NaN   

   causaneg3      peso  
0        NaN  1.040102  
1        NaN  0.938927  
2        NaN  0.838407  
3        NaN  0.938927  
4        NaN  1.096378  

[5 rows x 266 columns]

In [41]:
print(f"El dataset tiene {df.shape[0]} filas y {df.shape[1]} columnas")

El dataset tiene 111 filas y 266 columnas


In [53]:
df.dtypes

Encuestado    float64
País          float64
legis         float64
partido       float64
departa       float64
               ...   
resultado2    float64
causaneg2     float64
resultado3    float64
causaneg3     float64
peso          float64
Length: 266, dtype: object

In [100]:
#ID101: Posicionamiento Izq - Der de diputados: En una escala donde 1 es la Izquierda y 10 es la Derecha
df["ID101"].unique()

array([ 5.,  7.,  3.,  9.,  1.,  6.,  2.,  4., 99.,  8.])

In [104]:
#Eliminar categorías residuales
df = df[(df['ID101'] != 98) & (df['ID101'] != 99)] #Elimino valores de 98 (NS) y 99 (NC) de la variable
df["ID101"].unique() # Observacion: ningun diputado se coloca en el extremo de la derecha (10) pero sí en el extremo de la izq (1)

array([5., 7., 3., 9., 1., 6., 2., 4., 8.])

In [180]:
# PRO102:  Qué grado de importancia tiene hoy en Argentina la INSEGURIDAD como problema en la Arg, siguiendo una escala de 1 a 10, donde 1 significa "no es unacuestión importante" y el 10 "es una cuestión muy importante"?
df["PRO102"].unique() 

array([ 7.,  9., 10.,  3.,  8.,  4.,  5.,  6.])

In [186]:
#ANÁLISIS 1
#Correalción  - Importancia de la Inseguridad como problema (PRO113)
corr = df["ID101"].corr(df["PRO102"])
print(f'Correlación de Pearson: {corr:.2f}')

Correlación de Pearson: 0.44


In [192]:
#Regresión Lineal Posicionamiento Político - Importancia de la Inseguridad como problema
# Paso 3: Ajustar el modelo de regresión lineal
x = sm.add_constant(df["ID101"])
y = df["PRO102"]

modelo_1 = sm.OLS(y, x).fit()

# Mostrar el resumen del modelo
print(modelo_1.summary())

                            OLS Regression Results                            
Dep. Variable:                 PRO102   R-squared:                       0.192
Model:                            OLS   Adj. R-squared:                  0.185
Method:                 Least Squares   F-statistic:                     25.69
Date:                Fri, 25 Oct 2024   Prob (F-statistic):           1.67e-06
Time:                        18:39:12   Log-Likelihood:                -198.68
No. Observations:                 110   AIC:                             401.4
Df Residuals:                     108   BIC:                             406.8
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.0710      0.393     15.461      0.0

In [ ]:
#---------------

In [51]:
print(df[['SOCD7','ING3']])

                                          SOCD7  \
0              Universitarios de grado superior   
1                                     Postgrado   
2                                     Postgrado   
3                                     Postgrado   
4    Universitarios de grado medio o asimilados   
..                                          ...   
106            Universitarios de grado superior   
107                                   Postgrado   
108            Universitarios de grado superior   
109            Universitarios de grado superior   
110            Universitarios de grado superior   

                               ING3  
0    Categoría A: de 1.000 a 2.000$  
1    Categoría A: de 1.000 a 2.000$  
2    Categoría B: de 2.001 a 4.000$  
3    Categoría C: de 4.001 a 5.500$  
4    Categoría A: de 1.000 a 2.000$  
..                              ...  
106  Categoría A: de 1.000 a 2.000$  
107  Categoría C: de 4.001 a 5.500$  
108  Categoría A: de 1.000 a 2.000$  
109  Ca

In [55]:
valores_socd7=df['SOCD7'].unique()
valores_ing3=df['ING3'].unique()

print('Valores únicos en SOCD7', valores_socd7)
print('Valores únicos en ING3', valores_ing3)

Valores únicos en SOCD7 ['Universitarios de grado superior', 'Postgrado', 'Universitarios de grado medio o asimilados', 'Secundarios o asimilados', 'Primarios']
Categories (5, object): ['Postgrado', 'Primarios', 'Secundarios o asimilados', 'Universitarios de grado medio o asimilados', 'Universitarios de grado superior']
Valores únicos en ING3 ['Categoría A: de 1.000 a 2.000$', 'Categoría B: de 2.001 a 4.000$', 'Categoría C: de 4.001 a 5.500$', 'Categoría D: de 5.501 a 7.000$', 'Categoría F: de 8.501 a 10.000$', 'N.C.']
Categories (6, object): ['Categoría A: de 1.000 a 2.000$', 'Categoría B: de 2.001 a 4.000$', 'Categoría C: de 4.001 a 5.500$', 'Categoría D: de 5.501 a 7.000$', 'Categoría F: de 8.501 a 10.000$', 'N.C.']


In [59]:
x = df['SOCD7']
y = df['ING3']
x = sm.add_constant(x)
modelo = sm.OLS(y,x).fit()
print(modelo.summary())

ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).